language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install

script: phpunit --coverage-text

tools:
    php_code_coverage: true

notifications:
  email:
    - llewellynthomas@mac.com
